on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Befoer'
        run: pwd

      - uses: actions/checkout@v3 

      - name: 'After'
        run: pwd
